### PR TITLE
Allow to change map colors

### PR DESCRIPTION
**Pull request by P1-Ro**
Since [ICantBelieveItsNotValetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo) is deprecated and it mentions your repo as successor. 

I've noticed that there is no possibility to change colors. Since I've used this feature I think it would be cool to add to your project as well.

### CODE REVIEW

**Comment by erkexzcx** [comment]
Hey. Thank you for your PR.

IMO this would break config for everyone who simply do a regular update. I assume you would need to implement _default colors if not set_ logic. Would you be able to do it?

**Comment by strange-v** [comment]
Cool, I was searching for this feature.

**Comment by P1-Ro** [comment]
@erkexzcx I've added default colors

**Comment by jensweimann** [comment]
I've tried it, looking good! 
image

**Review by erkexzcx — APPROVED** [review]
Looking good!

**Comment by erkexzcx** [comment]
Hey there. Thanks again for your PR.

Currently I had a lot going on in my life and haven't got time for this project. On top of that, I no longer have roborock vacuum robot, but planning to get one in the future, so therefore your PR is the last one for now. Added disclaimer to README.md for now and will remove that disclaimer in the future when I get back to this project. :)

**Pull request merged**
